name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  scanning:
      name: GitGuardian scan
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # fetch all history so multiple commits can be scanned
        - name: GitGuardian scan
          uses: GitGuardian/ggshield/actions/secret@v1.29.0
          env:
            GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
            GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
            GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
            GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
            GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
  mvn-build:
    needs: scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile and test with Maven
      run: mvn clean install
      env:
        SQLUSER: ${{ secrets.SQLUSER }}
        CONNECTION: ${{ secrets.CONNECTION }}
        SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
  docker-build:
    needs: mvn-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile and test with Maven
      run: mvn clean package
      env:
        SQLUSER: ${{ secrets.SQLUSER }}
        SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
        CONNECTION: ${{ secrets.CONNECTION }}
        
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: daaddo/redis-bridge:latest

